### ISSUE TITLE
HIGH PRIORITY FRONTEND PUNCHLIST: CBO selector

### ISSUE THREAD

**Issue by arouault** [MAPC/dyee-dashboard#19]
- [x] (Filter applicants where their interests match with position categories) pull in real applicant data for all category-matching applicant information (name, return Y/N, grade, age, essay, and all other applicant info possible to import). #21

- [x] Connect to backend for checkboxes to indicate whether a CBO "intend to hire" "currently interviewing" or "not interested" #22

DUE BY FRIDAY AT THE LATEST

**Comment by allthesignals** [comment]
> category-matching applicant information
@arouault Sorry I don't follow what this means? Do CBOs go to the list and they can sort by category?

**Comment by arouault** [comment]
"category-matching applicants" = applicants whose selected categories (ie, Arts and Science) match with employer's job Categories (BCYF Camp, Arts and Science Position) 

ie We only show applicants who match to a job position category

**Comment by allthesignals** [comment]
Gotcha - in the UI for CBOs, only show applicants whose interests match categories of available positions. The reason this is confusing is "pull in real applicant data" sounds like a data migration task - this is really just a filter on the data. So the view just needs to filter.

**Comment by allthesignals** [comment]
Right, so to spec this out further, when a CBO logs in, they are able to see their open positions, and then it filters for applicants who match all of their open positions' categories.
