### ISSUE TITLE
Job Picker: Add "I'm Done" Button that submits final choices

### ISSUE THREAD

**Issue by arouault** [MAPC/dyee-dashboard#27]
Create a button to submit final job choices. Alert youth that this is their final decision and that these results will be sent to potential employers. 

Also Add text to confirmation message:

"Pro tip: Email or call an employer directly to find out more about the job and let them know you'd like an interview."

**Comment by allthesignals** [comment]
@arouault this has been addressed - once you sign off on it I'll close the issue.
