### ISSUE TITLE
CBO Portal: Add helper text above table

### ISSUE THREAD

**Issue by arouault** [MAPC/dyee-dashboard#30]
@allthesignals Please insert this text: 

Welcome <site_name>,

You have been allotted <open_position 50% rounded down> positions to select directly for summer employment at your job site. Your remaining <open_position 50% rounded up> positions will be selected through the City of Boston's Summer Jobs Lottery. 

In the list below, you can browse information about applicants who are interested in working at your site or in the same job category that you offer. You are required to review candidates here, and mark "Intend to Hire" or "I do not want to hire" by April 28th. 

This information will be used to track who you want to hire for HR purposes and to pool any remaining candidates into the lottery. Please note: You are responsible for communicating directly with youth applicants to interview or evaluate for employment. 

@mzagaja please do calculation in serializer for rounded up/down positions

**Comment by allthesignals** [comment]
Closing, see staging to verify

![image](https://cloud.githubusercontent.com/assets/5004319/24555093/dcfee59c-15fd-11e7-96ed-074fd7f073be.png)

**Comment by arouault** [comment]
Please add further edited text, now hemingway approved:

The Youth Summer Jobs Program has allocated you a total of 23 positions. You may select 50% of your positions (23 youth) to work for you this summer. In May 2017, the City of Boston will select the remaining 50% of your positions (23 youth) through a jobs lottery.

In the list below, browse through applicants who have an interest in the positions or area of work you offer. You must review candidates and mark "Intend to Hire" or "I do not want to hire" by April 28th. Any remaining youth applicants enter into the jobs lottery.

Your selections create an official record of who you want to hire.  It is mandatory to select applicants by April 28th to complete legal and HR requirements for employing youth. 

Note: The City of Boston will not be contacting any youth on your behalf. You are responsible for contacting youth and evaluating them for your programs.

**Comment by allthesignals** [comment]
![image](https://cloud.githubusercontent.com/assets/5004319/24563098/4c9ebb80-161b-11e7-89da-8e8e3e689f72.png)
