### ISSUE TITLE
CBO Portal: Add Boston.gov banner

### ISSUE THREAD

**Issue by arouault** [MAPC/dyee-dashboard#31]
An official header that can be included by sites that are official City websites, but not Boston.gov. To get the header installed, owners of the site need to get this javascript included in the HTML of their site.

 <script src="https://cob-header.herokuapp.com/header.js" async=true></script>

**Comment by allthesignals** [comment]
@arouault this is already installed? It won't work on staging because that domain hasn't been verified, but youthjobs.mapc.org has. Did you mean something else?
