### ISSUE TITLE
REQUIRED TODAY: CBO portal text changes

### ISSUE THREAD

**Issue by arouault** [MAPC/dyee-dashboard#33]
Change table headers:

category teens change to: "Teens who may be interested:"
job flag teens change to "Teen applicants who are interested in your jobs"

---
The BCYF Youth Engagement and Employment Summer Jobs Program has allocated you a total of 60 positions. You may select 50% of your positions (30 youth) to work for you this summer. In May 2017, the BCYF will select the remaining half of your positions (30 youth) through a jobs lottery.

In the list below, browse through applicants who have an interest in the position or area of work you offer. Starting April 5th, you may review candidates and mark "Intend to Hire" or "I do not want to hire." Any remaining youth applicants enter into the jobs lottery.

Please add your choices beginning April 5th and no later than April 28th. Your selections create an official record of who you want to hire. **It is mandatory to select applicants by April 28th to complete legal and HR requirements for employing youth.**

_Note: The City of Boston's Division of Youth Engagement and Employment will not be contacting any youth on your behalf. You are responsible for contacting youth and evaluating them for your programs._

**Comment by allthesignals** [comment]
![image](https://cloud.githubusercontent.com/assets/5004319/24571047/e5f2aa96-163c-11e7-986d-771a1db609d3.png)

**Comment by arouault** [comment]
Had to change text. Please redo this task for body text.

**Comment by arouault** [comment]
More text changes :1st_place_medal: please re-add
