### ISSUE TITLE
URGENT CBO Portal: Fix Calculation of open_positions in Positions Table

### ISSUE THREAD

**Issue by arouault** [MAPC/dyee-dashboard#34]
Fix calculation to reflect 

Total Allottments = open_positions column for one site name (NOTE: there will be multiple positions for each site. Select only one) 
![screen shot 2017-04-03 at 6 14 26 pm](https://cloud.githubusercontent.com/assets/1305629/24633969/68d36154-1899-11e7-903b-10cdeef4af07.png)

Lottery allottments = open_positions*.5 rounded up
Direct selection allottments = open_positions*.5 rounded down

Currently, the calculation is summing all requisitions. 

This is presented in introduction text in CBO Portal and should inform how many slots CBOs may fill. 

![screen shot 2017-04-03 at 6 12 29 pm](https://cloud.githubusercontent.com/assets/1305629/24633955/52731a58-1899-11e7-99f1-e602674eaca2.png)

+ Once closed please undo the commented-out text in intro paragraph.

**Comment by allthesignals** [comment]
![image](https://cloud.githubusercontent.com/assets/5004319/24725871/5449c76a-1a1e-11e7-89de-a474036a4630.png)
A fix has been pushed - please check to see that it's doing this correctly. I did several manual checks and it looks good.

**Comment by allthesignals** [comment]
@arouault is this good to close?

**Comment by arouault** [comment]
Yes. Closed! @allthesignals
