### ISSUE TITLE
CBO Portal Pick and Requisition Status

### ISSUE THREAD

**Issue by mzagaja** [MAPC/dyee-dashboard#40]
We need the front-end to update the status of all the CBO associated Picks and Requisitions to "hire" in order for ICIMS to update. My thought is the way it will work is that we create the associations the way we do now, and then update the status when folks click the "submit" button. If you have any questions let me know.

**Comment by allthesignals** [comment]
![image](https://cloud.githubusercontent.com/assets/5004319/25236850/f0cff5fc-25b6-11e7-8e52-26405916c27d.png)
