### ISSUE TITLE
Job Picker Dashboard: Add contact info under map for CBO Partners

### ISSUE THREAD

**Issue by arouault** [MAPC/dyee-dashboard#6]
Add in fields including primary contact name, email, phone, and site address and any other information associated in the table with the partner site.

**Comment by arouault** [comment]
Not complete. Please add address.

**Comment by allthesignals** [comment]
Doesn't seem like `address` is available? @mzagaja says we just store lat/lon. We might have to reverse-geocode.

**Comment by arouault** [comment]
Already lives in the original Carto file. https://mapc.carto.com/u/mapc-admin/tables/job_descriptions_address
