### ISSUE TITLE
Job Picker Dashboard: Link to SuccessLink

### ISSUE THREAD

**Issue by arouault** [MAPC/dyee-dashboard#7]
Add a link on the picker dashboard that points to the official successlink login https://successlink-boston.icims.com/jobs/login?loginOnly=1&redirect=&hashed=-435683065

**Comment by allthesignals** [comment]
@mzagaja any ideas on how this link is generated? I'm not seeing it on the model...

**Comment by mzagaja** [comment]
It's just a static link to add to the view, they're not getting a customized link for them.

**Comment by allthesignals** [comment]
Ooooh okay! I was confusing this with #3, which I also don't see.

**Comment by allthesignals** [comment]
@arouault where should this go?
